# Generated by Django 2.2.12 on 2020-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('EmployeeId', models.IntegerField(max_length=100)),
                ('LastName', models.DateTimeField(auto_now_add=True)),
                ('PhoneNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
