# Generated by Django 2.2.12 on 2020-11-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeId',
            field=models.IntegerField(unique=True),
        ),
    ]
